### ISSUE TITLE
Feature Request: Support for runtime config?

### ISSUE THREAD

**Issue by Zibbp** [richardeschloss/nuxt-socket-io#128] opened 2020-07-27 02:53 UTC
I was wondering if there is support for the new [runtime config](https://nuxtjs.org/guide/runtime-config/) allowing environment variables to be set after build (during start).

I'm asking this because I need a way to set the socket url after the build and during runtime of the application. Normal environment variables can only be added during the build.

**Comment by richardeschloss** [comment] 2020-07-27 04:39
I have to learn about the new runtime config. I'm not as familiar with that. In the current implementation, the url has been abstracted out of the plugin, but I guess the way to solve it would be to having an override that you pass in.

**Comment by Zibbp** [comment] 2020-07-27 16:45
From my testing that won't work as normal environment variables will only be injected during build and not during start unless using the runtime variables or having nuxt commit the variables into the store like so
```bash
export const actions = {
  nuxtServerInit({ commit }) {
    if (process.server) {
      commit("setEnv", {
        BASE_URL: process.env.BASE_URL
      });
    }
  }
};
```
I could

**Comment by richardeschloss** [comment] 2020-07-27 19:39
Currently, the url can only be set in one place...the nuxt config.  That nuxt config can consume env vars, but to do exactly what you want, I need to put a bit more thought into providing a proper solution. I could consider allowing `url` to be an argument that the plugin uses. However,I think the solution for runtime should ultimately use the injected `$config` that Nuxt provides. I think perhaps `this.$config.io` would hold all the runtime socket.io stuff. I also have to make sure I have proper checks in place to avoid any kind of regressions.

In this repo, the main file I'll be experimenting with is `io/plugin.js`, if it helps. If you already have a fork of this working before I do, please use the branch name "feature/128" so I can easily organize things. Thanks.

**Comment by richardeschloss** [comment] 2020-07-27 19:45
Can you please also provide clarification on why the socket IO url isn't known at build time?

**Comment by Zibbp** [comment] 2020-07-27 20:52
The socket IO url isn't know at build time because it's a docker container that is meant to be deploy on many different domains, each having a different url. During the docker image build runtime variables that change between each application are gathered via a docker env variable so users can add `-v IO_URL=myurl.com` to set the socket IO url but then the issue arises that I can't set that socket URL within the app because the nuxt.config.js can't read runtime variables.

I'm probably overthinking this and can't seen to find a solution to have a dynamic socket.io url set by a docker environment variable.

**Comment by richardeschloss** [comment] 2020-07-27 21:21
I have a push coming that I think will do what you want.

**Comment by richardeschloss** [comment] 2020-07-27 21:29
Ok, branch [feat/issue128](https://github.com/richardeschloss/nuxt-socket-io/tree/feat/issue128) pushed, with very simple changes. The plugin was updated to merge in the build-time io config with the run-time config. run-time config will take priority (and overwrite build time). The io options you pass to the runtime config are exactly the same:

`nuxt.config`:
```js
publicRuntimeConfig: {
    io: {
      sockets: [
        {
          name: 'publicSocket',
          url: 'url1'
        }
      ]
    }
  },
  privateRuntimeConfig: {
    io: {
      sockets: [
        {
          name: 'privateSocket',
          url: 'url2'
        }
      ]
    }
  }
}
```

This approach can further be simplified if you import your io configs:

```js
import io from 'io.runtime.config'
import ioDev from 'io.dev.config'

export default {
  publicRuntimeConfig: { io }
}
```

So, to toy with it, just need to copy in the plugin.js file into your node_modules/nuxt-socket-io/io folder. Can you please let me know how far you get with this? It works for me. Tried both with the private vars and public.

**Comment by Zibbp** [comment] 2020-07-27 22:15
Testing while running in development mode works perfectly, without issues. I'm able to set and use the URL via an environment variable via cross-env.
What I found that doesn't work is when the nuxt project is built using `npm run build` then started with the same environment variable from before it will not use the runtime config but will fallback and only use the standard IO settings object in the nuxt.config file.

Also, thanks for pushing out these updates, really do appreciate it 😄

**Comment by richardeschloss** [comment] 2020-07-27 22:23
Hmm, I'm surprised it's not working after npm run build. Can you pull the latest commit I had? I think I pushed a minor change a few minutes after I first mentionned the push, that should fully merge the options.

**Comment by Zibbp** [comment] 2020-07-27 22:41
After some testing I found out the cause was on my end. I wasn't using the latest plugin.js file for my build. After updating the plugin it is running perfectly and completely fixes the issue letting me dynamically set the socket io url. I'll continue to play around with it and let you know if I find any issues.
Thanks again!

**Comment by richardeschloss** [comment] 2020-07-27 23:02
Ok. I'll be away from keyboard but should be back tonight. I'll try to get the automated tests and code cleaned up tonight or tomorrow. (tests to also ensure no regressions)

**Comment by richardeschloss** [comment] 2020-07-28 04:39
v1.1.6 released with feature.

**Closed by richardeschloss** 2020-07-28 04:39 UTC
