### ISSUE TITLE
[@next] Server doesn't come back upon restarting nuxt3 server

### ISSUE THREAD

**Issue by peteromano** [richardeschloss/nuxt-socket-io#257] opened 2022-02-06 18:04 UTC
Install nuxt-socket-io@next in nuxt3 project

Add:

```
  modules: [
    'nuxt-socket-io',
    ...
  ],
```

Start nuxt3

Go  to http://localhost:<YOUR_PORT>

Save nuxt.config.ts (to restart nuxt)

Wait for nuxt restart, as normal

Go  to http://localhost:<YOUR_PORT>

Result:

![image](https://user-images.githubusercontent.com/392387/152694722-18cf39f6-d04f-4d3f-906a-41f5a833bca2.png)

Commenting the nuxt-socket-io module works as expected/normal.

**Comment by peteromano** [comment] 2022-02-06 18:10
There are no errors outputting to the CLI, and it's not crashing the nuxt3 server.. I'm guessing some nuxt-socket-io middleware is just nulling out the server response after the restart or something..

Probably, when nuxt3 restarts, io server also has to restart?

**Comment by richardeschloss** [comment] 2022-02-06 21:05
Can you please clarify: are you specifically commenting / uncommenting out the modules? I believe the issue you're seeing is more Nuxt3-related because the module code seems to only run at boot (i.e., modules are only installed once). 

I can repro similar behavior if I comment/uncomment out the "nuxt-socket-io" line, but I believe the issue is it's not getting a second chance to run again after HMR. I can verify this by placing a log statement in the module's setup function (that only gets logged once :( ).

**Comment by peteromano** [comment] 2022-02-06 21:34
Right, so the nuxt-socket-io code would have to run on a nuxt hook or something. Nuxt team is aware of the issue, but for now, I mentioned that they likely dont have to do anything on their end, _unless_ they need to be a provide an event hook or something

**Comment by peteromano** [comment] 2022-02-06 21:36
"Comment" , i just meant removing it from the modules. Al;so, this isnt HMR, its literally when restarting nuxt, which happens on saving nuxt.config.ts for example. 

I use containers, with other services, so even if SIGINT'ing and restarting were a solution, that would be a bad DX with containers. Either way, it should be fixed somehow

**Comment by richardeschloss** [comment] 2022-02-07 01:51
Ok, I figured out what was going on. For the time being, please comment out this line, and it should all work fine now:

(in your end, it'd be node_modules/nuxt-socket-io/lib/module.js)
https://github.com/richardeschloss/nuxt-socket-io/blob/04fe31c1fa0876d24c5e4711cfd203bf3624aa3b/lib/module.js#L204

So the Nuxt restarts were actually calling setup() again, but it was the listen hook only being called once. The close hook was part of a cleanup step that was inadvertently closing the Nuxt server too.  I was expecting the listen hook would get called again and that it wouldn't matter. But apparently it did. I still think I want to have that cleanup code in there, just disabled by default.

**Comment by richardeschloss** [comment] 2022-02-07 04:35
3.0.4. pushed with the necessary changes. This will require one config item:

nuxt.config:
```js
export default { 
  io: {
    server: { teardown: false } 
  }
}
```

This will prevent the server from automatically closing and will stay alive when Nuxt restarts.

**Closed by richardeschloss** 2022-02-07 04:35 UTC

**Comment by dladeira** [comment] 2023-01-03 07:22
@richardeschloss 

On the latest version of Nuxt3, if you don't include `server: { teardown: false }` in nuxt.config.ts, when you update the config, the server will throw and error and nuxt will fail to automatically restart. A manual restart is required (running `npm run dev` again).

Maybe this should be included in the docs or readme? It's a important problem and the solution shouldn't be in a closed issue.


package.json:
```
"devDependencies": {
    "nuxt": "3.0.0"
  },
  "dependencies": {
    "@nuxt-alt/proxy": "^2.1.3",
    "@nuxt/image-edge": "^1.0.0-27840416.dc1ed65",
    "chart.js": "^4.1.1",
    "nuxt-proxy": "^0.3.4",
    "nuxt-socket-io": "^3.0.12",
    "sass": "^1.56.2",
    "sass-loader": "^10.4.1",
    "vue-chartjs": "^5.1.0"
  }
```

nuxt.config.js:
```
export default defineNuxtConfig({
    css: [
        '@/assets/styles/global.scss'
    ],
    vite: {
        css: {
            preprocessorOptions: {
                scss: {
                    additionalData: '@import "@/assets/styles/variables.scss";'
                }
            }
        },
    },
    modules: [
        'nuxt-proxy',
        '@nuxt/image-edge',
        'nuxt-socket-io'
    ],
    io: {
        server: { teardown: false }, // The important line
        sockets: [
            {
                name: 'main',
                url: process.env.SOCKET_SERVER,
                default: true
            }
        ]
    },
    runtimeConfig: {
        proxy: {
            options: [{
                target: process.env.API_SERVER,
                changeOrigin: true,
                pathRewrite: {
                    '^/api': '/'
                },
                pathFilter: [
                    '/api'
                ]
            }]
        },
        public: {
            origin: process.env.ORIGIN
        }
    }
})
```

Error Log:
```
Nuxi 3.0.0                                                                                                                                  08:15:02
Nuxt 3.0.0 with Nitro 1.0.0                                                                                                                 08:15:02
                                                                                                                                            08:15:03
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.100.100:3000/


 ERROR  (node:651162) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time                  08:15:03
(Use `node --trace-warnings ...` to show where the warning was created)

ℹ Vite client warmed up in 1506ms                                                                                                           08:15:05
✔ Nitro built in 265 ms                                                                                                               nitro 08:15:06
(node:651162) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time                          08:15:07
(Use `node --trace-warnings ...` to show where the warning was created)
ℹ nuxt.config.ts updated. Restarting nuxt...                                                                                                08:15:15
                                                                                                                                            08:15:02
 ERROR  Cannot restart nuxt:  Cannot read properties of null (reading 'port')                                                               08:15:15

  at load (node_modules/nuxi/dist/chunks/dev.mjs:6783:54)
  at async _applyPromised (node_modules/nuxi/dist/chunks/dev.mjs:6713:10)

ℹ socket.io server listening on localhost:3000
```
(running node v19.0.0)

**Comment by richardeschloss** [comment] 2023-01-03 18:02
Hi, it's documented here: https://nuxt-socket-io.netlify.app/usage#auto-teardown
